#!/bin/bash

num=$1
n_max=67280421310721


if [ -z "$1" ]
  then
    echo "Please enter a non-negative int number."
    exit 1
fi

expr $num + 1 > /dev/null 2>&1

if [ $? -ne 0 ]
  then
    echo "Sorry. $num is -1 or not an int number."
    exit 1
  else
    if [ $num -le 0 ]
      then
        echo "Sorry. $num is a negative number or zero."
        exit 1
      else
        if [ $num -gt $n_max ]
          then
            echo "Sorry. $num is too large."
            exit 1
        fi
    fi
fi

num_sqrt=`echo "$num" | awk '{print int(sqrt($1))}'`
num_div=0

#echo "num_sqrt=$num_sqrt"

if [ $(($num_sqrt*$num_sqrt)) = $num ]
  then
    echo "$num is not a prime number."
    echo "divisor of $num: $num_sqrt"
    exit 0
  else
    for (( i=2 ; i<=$num_sqrt ; i++)); do
#     echo "i=$i"
#     echo "$num%$i=$(($num%$i))"
      if [ $(($num%$i)) -eq 0 ]
        then
          echo "$num is not a prime number."
          echo "divisor of $num: $i"
          exit 0
      fi
    done
    echo "$num is a prime number!!"
    exit 0
fi

exit 1
